from pydantic import BaseModel


#  Define the model for the URL Response
class CreateShortUrlResponse(BaseModel):
    # short_url is the short url generated by the server
    longurl: str
    shorturl: str
